### ISSUE TITLE
Error occurred installing jupyterlab-flake8

### ISSUE THREAD

**Issue by cristinaserrano** [mlshapiro/jupyterlab-flake8#19] opened 2019-08-20 07:53 UTC
Hi, Mr. Shapiro.
I am now getting this installation error with following versions of jupyterlab:

Current versions:
jupyterlab==1.0.2
jupyterlab-git==0.5.0
jupyterlab-server==1.0.0

Error (while installing using jupyter lab graphic extension):
An error occurred installing jupyterlab-flake8.

Error message:

This extension does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension      Package
>=1.0.1 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/application
>=1.0.1 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/apputils
>=3.0.0 <4.0.0          >=2.2.1 <3.0.0 @jupyterlab/coreutils
>=1.0.1 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/fileeditor
>=1.0.1 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/notebook
>=1.0.1 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/terminal

I think this is the same situation as #8, #11 issue. Could you help me avoid this error?

**Comment by Sevastiyan** [comment] 2019-08-21 06:26
I am having the same error. Its just that the extension is not yet compliant with the current 1.0 version of Jupyter Lab. This happens to everyone who updates to the official release of Jupyter Lab. I think it works with Jupyter Notebooks, but haven't tried myself yet. Hope the development gets resumed for the extension to make the update. Jupyter definitely needs a good linter and this is the one that meets the needs of almost everyone writing code with Jupyter.

**Comment by memeplex** [comment] 2019-09-09 17:29
Same here with Jupyterlab 1.1.1.

But the problem is:

![image](https://user-images.githubusercontent.com/2845433/64552705-29744780-d30e-11e9-9d1f-da323b6b879c.png)

while trying to install this extension.

**Comment by mlshapiro** [comment] 2019-09-10 13:00
should be fixed in 0.3.0. Thanks for the alert!

**Closed by mlshapiro** 2019-09-10 13:00 UTC

**Comment by memeplex** [comment] 2019-09-11 12:48
Fixed, thanks!

**Comment by cristinaserrano** [comment] 2019-09-11 18:41
Works as a charm. Thanks!!!!
